spring:
  redis:
    host: 47.120.9.82
    port: 6379
    password: ZQBT1314.
    jedis:
      pool:
        max-wait: -1
        time-between-eviction-runs: 10000

  mvc:
    throw-exception-if-no-handler-found: true
    format:
      date: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: true

  #文件配置
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  aop:
    proxy-target-class: true
    auto: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/graduatestudent?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    username: graduatestudent
    password: 123456
# 日志
logging:
  pattern:
    file: "my.log.%d{yyyy-MM-dd}.log"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
    path: "./logs"
  logback:
    rollingpolicy:
      max-history: 30
      max-file-size: 10MB
  level:
    com.example.graduatestudent: debug
    com.example.graduatestudent.mapper: debug

